# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "load_image",
    "load_image_bytes",
    "load_image_bytes_into",
    "load_image_into",
    "unload_texture",
]

def load_image(path: builtins.str, name: builtins.str, outer: typing.Optional[builtins.str] = None, mips: builtins.bool = True, srgb: builtins.bool = True, flip: builtins.bool = False, tiling: builtins.bool = False, address_x: typing.Optional[builtins.str] = None, address_y: typing.Optional[builtins.str] = None, filter: typing.Optional[builtins.str] = None, lod_group: typing.Optional[builtins.str] = None) -> builtins.str:
    r"""
    Loads an image file (PNG or JPEG) as a new `Texture2D` and returns its
    full object path (e.g. `"Transient.MyMod.logo"` — resolve it with
    `unrealsdk.find_object("Texture2D", path)`). `name` is required. `outer`
    optionally names an existing object to construct under (e.g. a `Package`),
    defaulting to the engine's `Transient` package. Name collisions
    get an automatic `_1`-style suffix. Textures are sRGB by default,
    GC-immune and live for the session (`unload_texture` releases one).
    Edge addressing is `"clamp"` by default — `"wrap"`/`"mirror"` (also per
    axis via `address_x`/`address_y`) set `AddressX`/`AddressY`; `filter` is
    `"linear"` (default) or `"nearest"`; `lod_group` names a `TextureGroup`
    entry (`"ui"`, `"effects"`, …) resolved through the engine's own enum,
    `None` leaves the engine default; `flip` mirrors the source art
    vertically at load; `tiling` clears the engine's `bNoTiling` hint for
    wrap-style art. Images larger than 2048px in either dimension are
    downscaled (aspect-preserving) with a log note.
    """

def load_image_bytes(data: typing.Sequence[builtins.int], name: builtins.str, outer: typing.Optional[builtins.str] = None, mips: builtins.bool = True, srgb: builtins.bool = True, flip: builtins.bool = False, tiling: builtins.bool = False, address_x: typing.Optional[builtins.str] = None, address_y: typing.Optional[builtins.str] = None, filter: typing.Optional[builtins.str] = None, lod_group: typing.Optional[builtins.str] = None) -> builtins.str:
    r"""
    Like [`load_image`] for in-memory image bytes (PNG or JPEG).
    """

def load_image_bytes_into(data: typing.Sequence[builtins.int], target: builtins.str, mips: builtins.bool = True) -> builtins.str:
    r"""
    Like [`load_image_into`] for in-memory image bytes.
    """

def load_image_into(path: builtins.str, target: builtins.str, mips: builtins.bool = True) -> builtins.str:
    r"""
    Replaces an existing texture's content: decodes `path` (PNG or JPEG) and
    swaps it into the `Texture2D` at `target` (full object path).
    Always uploads BGRA (the target's format property may be changed).
    """

def unload_texture(path: builtins.str) -> builtins.bool:
    r"""
    Releases a texture created by [`load_image`] to the garbage collector
    (clears its `Standalone` flag). Returns whether the path was found
    """

